swagger: "2.0"

################################################################################
#                           Service Metadata                                   #
################################################################################
info:
  version: 1.0
  title: My service name
  description: A full description of the service. Can contain HTML tags.
  contact:
    name: maintainer name
    email: maintainer@murano.com

################################################################################
#                            API Information                                   #
################################################################################
host: domain.of.your.service
basePath: /
x-healthPath: /health # This endpoint needs to return 2xx status code. If omitted basePath is used

################################################################################
#                                Operations                                    #
################################################################################
paths:
  /operation:
    get:
      description: At least one operation is required.
      operationId: myOperation # Used as Scripting function call
      x-example: | -- A valid script example

                  local result = MinimalService.myOperation()
      responses:
        200: # Http status code is not returned to the scripting result
          description: Return the operation result
          schema:
            description: Operation results
            type: string
