swagger: "2.0"
info:
  version: v1
  title: Service name
  description: This is a minimal service definition for a Storage service with quota limitation.
  contact:
    name: maintainer name
    email: maintainer@service.com # Used by Murano for service outage notification
tags:
  - name:         keyword
    description:  Murano use it to reference the service

host: domain.of.your.service
basePath: /
x-healthPath: /health # this endpoint needs to return 2xx status code, if omitted "/" is used

# Solution lifecycle management endpoints
x-init: createSolution # Triggered by Murano when a solution is created
x-info: getSolution # Triggered by Murano to get a solution information
x-update: updateSolution # Triggered by Murano when a solution is updated
x-gc: delSolution # Triggered by Murano when a solution is removed

paths:
  # Murano Admin endpoint used for solution storage namespace management
  /{solution_id}:
    parameters:
      - name: solution_id
        type: string
        in: path
        description: The solution identifier. Set automatically.
        required: true
    post:
      description: Used by Murano to create a solution namespace.
      operationId: createSolution
      x-internal-use: true # Indicate that this operation cannot be called from user scripts
      parameters:
        - name: settings
          in: body
          description: The service settings for a solution.
          required: true
          schema:
            $ref: "#/definitions/SolutionSettings"
      responses:
        201:
          description: Solution successfully created
    get:
      description: Used by Murano to get the solution settings.
      operationId: getSolution
      x-internal-use: true
      responses:
        200:
          description: Solution settings & usage
          schema:
            $ref: "#/definitions/SolutionInfo"
    put:
      description: Used by Murano to update the solution settings.
      operationId: updateSolution
      x-internal-use: true
      parameters:
        - name: settings
          in: body
          description: The service settings for a solution.
          required: true
          schema:
            $ref: "#/definitions/SolutionSettings"
      responses:
        204:
          description: Settings updated
    delete:
      description: Used by Murano to remove a solution and clean its namespace.
      operationId: delSolution
      x-internal-use: true
      responses:
        204:
          description: Solution successfully removed.

  # Service operations
  /{solution_id}/data:
    parameters:
      - name: solution_id
        type: string
        in: path
        description: The solution identifier. Set automatically by Murano at service call.
        x-internal-use: true # Indicate that this parameters cannot be used from user scripts
        required: true
    post:
      description: Save data to the solution namespace.
      operationId: setData
      responses:
        201:
          description: Solution successfully created
    get:
      description: Retrieve data from the solution namespace.
      operationId: getData
      responses:
        200:
          description: Successfully returned the solution data
          schema:
            description: The solution data
            type: string

definitions:
  Quota:
    type: object
    description: This object contains numeral metrics limitation.
    properties:
      metricName:
        type: integer
        description: This is a metric used to limit the service usage for a solution.

  SolutionSettings:
    description: The service settings for a solution.
    type: object
    properties:
      quota:
        $ref: "#/definitions/Quota"

  SolutionInfo:
    description: The service settings & usage for a solution.
    type: object
    properties:
      quota:
        $ref: "#/definitions/Quota"
      usage:
        type: object
        description: This object contains numeral metrics usage for a given solution.
        properties:
          metricName:
            type: integer
            description: The current usage of the service.

